server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: zuul-server
zuul:
  routes:
    userapi:
      path: /userapi/**
      serviceId: user
    articleapi:
      path: /articleapi/**
      serviceId: article
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
